meta-pytorch/tokenizers

CMakeLists.txt
Summary: As titled. When we use tokenizers as a dependency project, we need to use `CMAKE_CURRENT_SOURCE_DIR` to refer to the root directory of `tokenizers`.
Test Plan:
Reviewers:
Subscribers:
Tasks:
Tags:
=> Change CMAKE_SOURCE_DIR to CMAKE_CURRENT_SOURCE_DIR

src/sentencepiece.cpp
Summary:
Example error message:
```
couldn't load runner/third-party/tokenizers/test/resources/test_sentencepiece.model.
Error message:
model file path should not be empty.
It is likely that the tokenizer artifact is broken or of a different format.
```
Test Plan:
Reviewers:
Subscribers:
Tasks:
Tags:
=> Improve error message

pytorch_tokenizers/TARGETS, pytorch_tokenizers/__init__.py, pytorch_tokenizers/hf_tokenizer.py, pytorch_tokenizers/llama2c.py, pytorch_tokenizers/targets.bzl, pytorch_tokenizers/tiktoken.py, tools/llama2c/convert.py, tools/llama2c/targets.bzl
Summary:
Migrate usages of
```
fbcode//executorch/extension/llm/tokenizer:tokenizer_py
```
to use:
```
fbcode//pytorch/tokenizers/pytorch_tokenizers:tokenizers
```
Differential Revision: D69820450
=> Migrate extension/llm/tokenizer python users to use the new repo

targets.bzl, test/TARGETS, test/targets.bzl, test/test_llama2c_tokenizer.cpp, test/test_sentencepiece.cpp, test/test_tiktoken.cpp
TODO: 
buck changes
Test Plan
Build
```
cmake .     -DCMAKE_INSTALL_PREFIX=cmake-out -DTOKENIZERS_BUILD_TEST=ON -Bcmake-out
cmake --build cmake-out -j9 --target install
```
Test
```
(executorch) [lfq@devvm20128.prn0 /data/users/lfq/tokenizers/cmake-out (lfq.tokenizer-test)]$ ctest
Test project /data/users/lfq/tokenizers/cmake-out
Start 1: test_base64
1/5 Test #1: test_base64 ......................   Passed    0.00 sec
Start 2: test_llama2c_tokenizer
2/5 Test #2: test_llama2c_tokenizer ...........   Passed    0.00 sec
Start 3: test_pre_tokenizer
3/5 Test #3: test_pre_tokenizer ...............   Passed    0.73 sec
Start 4: test_sentencepiece
4/5 Test #4: test_sentencepiece ...............   Passed    0.04 sec
Start 5: test_tiktoken
5/5 Test #5: test_tiktoken ....................   Passed …
```
=> Tokenizer test

pyproject.toml, pytorch_tokenizers/tools/llama2c/convert.py, setup.py
Summary: As titled
Test Plan:
```bash
pip install .
```
Then in python
```python
from pytorch_tokenizers import HuggingFaceTokenizer, Llama2cTokenizer, TiktokenTokenizer
```
Reviewers:
Subscribers:
Tasks:
Tags:
=> Add setup.py

include/pytorch/tokenizers/tiktoken.h
Summary:
asserts are optimized away in opt mode: https://fb.workplace.com/groups/codetestingqa/permalink/276290840988681/
assert in the test: https://www.internalfb.com/code/fbsource/[1bbb7754f70b]/fbcode/pytorch/tokenizers/include/pytorch/tokenizers/tiktoken.h?lines=39
Differential Revision: D70428343
=> Fix tiktoken test

third-party/TARGETS
Summary: In order for ExecuTorch's buck build to work in oss we need this TARGETS file.
Test Plan:
Reviewers:
Subscribers:
Tasks:
Tags:
=> Add a TARGETS file for executorch's buck build in oss

targets.bzl
Summary: This diff extends the pytorch tokenizers.
Reviewed By: larryliu0820
Differential Revision: D70786405
=> Extending build systems to include FBCode

examples/tokenize_tool/main.cpp, test/test_base64.cpp, test/test_llama2c_tokenizer.cpp, test/test_pre_tokenizer.cpp, test/test_sentencepiece.cpp, test/test_tiktoken.cpp
Summary:
Test Plan:
Reviewers:
Subscribers:
Tasks:
Tags:
=> clang format the rest of code

.clang-format, src/pre_tokenizer.cpp, src/token_decoder.cpp, targets.bzl
Summary: As titled.
Test Plan:
Reviewers:
Subscribers:
Tasks:
Tags:
=> Add .clang-format

CMakeLists.txt, include/pytorch/tokenizers/bpe_tokenizer_base.h, include/pytorch/tokenizers/string_integer_map.h, include/pytorch/tokenizers/tiktoken.h, src/bpe_tokenizer_base.cpp, src/hf_tokenizer.cpp, src/tiktoken.cpp, test/fb/TARGETS, test/targets.bzl, test/test_string_integer_map.cpp
Summary:
This change ports the string_integer_map changes from D69472841 to pytorch.
The string_integer_map implementation has changed slightly.  The constructor now takes a container of std::pairs instead of an explicit std::unordered_map, allowing to be initialized from more allocation-friendly containers.  In tests on some devices, this change brings the allocation cost of a particular corpus down from 19.41MB to 3.23MB, while improving token lookup performance and maintaining a par for rank lookup.
Differential Revision: D71500411
=> Port string_integer_map and changes to tiktoken to pytorch

pytorch_tokenizers/targets.bzl
Summary:
X-link: https://github.com/pytorch/executorch/pull/9808
One missing item for the new tokenizer lib
Reviewed By: kirklandsign
Differential Revision: D72263224
=> fix qnn export

src/pre_tokenizer.cpp, test/test_pre_tokenizer.cpp
Was missing the "Regex" key, e.g.
```
"pretokenizers": [
{
"type": "Split",
"pattern": {
"Regex": "[^\\r\\n\\p{L}\\p{N}]?[\\p{Lu}\\p{Lt}\\p{Lm}\\p{Lo}\\p{M}]*[\\p{Ll}\\p{Lm}\\p{Lo}\\p{M}]+(?i:'s|'t|'re|'ve|'m|'ll|'d)?|[^\\r\\n\\p{L}\\p{N}]?[\\p{Lu}\\p{Lt}\\p{Lm}\\p{Lo}\\p{M}]+[\\p{Ll}\\p{Lm}\\p{Lo}\\p{M}]*(?i:'s|'t|'re|'ve|'m|'ll|'d)?|\\p{N}{1,3}| ?[^\\s\\p{L}\\p{N}]+[\\r\\n/]*|\\s*[\\r\\n]+|\\s+(?!\\S)|\\s+"
},
"behavior": "Removed",
"invert": true
},
...
]
```
Test (looking into addressing the invalid perl operator negative lookahead):
```
>> cmake-out/examples/tokenize_tool/tokenize_tool hf_tokenizer ~/hf/models--microsoft--Phi-4-mini-instruct/snapshots/c0fb9e74abda11b496b7907a9c6c9009a7a0488f/tokenizer.json "Hello world!"
WARNING: All log messages before absl::InitializeLog() is …
```
=> Update pattern key for split pretokenizer

.gitignore
Building `tokenizer` through ExecuTorch causes the submodule to become "dirty" due to untracked build artifacts. So, let's ignore them.
=> Include build files in gitignore

include/pytorch/tokenizers/tiktoken.h, src/bpe_tokenizer_base.cpp, src/tiktoken.cpp
=> Use common base class private functions for TikToken

include/pytorch/tokenizers/bpe_tokenizer_base.h, include/pytorch/tokenizers/hf_tokenizer.h, include/pytorch/tokenizers/pre_tokenizer.h, include/pytorch/tokenizers/result.h, include/pytorch/tokenizers/tiktoken.h, include/pytorch/tokenizers/token_decoder.h, src/bpe_tokenizer_base.cpp, src/hf_tokenizer.cpp, src/pre_tokenizer.cpp, src/tiktoken.cpp, src/token_decoder.cpp, targets.bzl, test/test_pre_tokenizer.cpp
🧱 Stack:
Pass CI
```
cmake -DTOKENIZERS_BUILD_TEST=ON -DCMAKE_BUILD_TYPE=Debug . -Bbuild && cmake --build build -j9 --config Debug
(cd build && ctest)
```
=> Decouple tokenizers from Re2 and use IRegex interface

.gitmodules, CMakeLists.txt, include/pytorch/tokenizers/pcre2_regex.h, src/pcre2_regex.cpp, src/regex.cpp, targets.bzl, test/test_regex.cpp
Adds pcre2 to handle the negative lookbehinds in HuggingFace tokenizers.
Performance stays about the same from test runs [before](https://github.com/pytorch-labs/tokenizers/actions/runs/14480863330/job/40617329721#step:14:758) (run on last commit on main) and [after](https://github.com/pytorch-labs/tokenizers/actions/runs/14526152504/job/40757962551#step:14:901) (this pr).
Tokenizer library size (from `ls -lh build/libtokenizers.a`): `13M` (on main) -> `15M`. This most likely comes from adding the `pcre2` lib.
🧱 Stack:
=> Add pcre2 as re2 fallback

include/pytorch/tokenizers/tokenizer.h
Otherwise not sure whether `bos_tok_ = 0` is initialized
=> Initialize bos_tok_ = 0 in tokenizer.h

targets.bzl, third-party/targets.bzl
Get https://github.com/pytorch-labs/tokenizers/pull/55 back in, which was closed because of a diff linked to two PRs
=> Pcre2 buck target in third-party (#55)

CMakeLists.txt, src/regex.cpp, targets.bzl
Make the pcre2 fallback optional to offer library size savings
```
cmake -DSUPPORT_REGEX_LOOKAHEAD=ON -DTOKENIZERS_BUILD_TOOLS=ON . -Bbuild && cmake --build build -j9
stat -f "%z %N" build/libtokenizers.a
6394880 build/libtokenizers.a
cmake -DTOKENIZERS_BUILD_TOOLS=ON . -Bbuild && cmake --build build -j9
stat -f "%z %N" build/libtokenizers.a 
6311960 build/libtokenizers.a
```
=> Gate regex lookahead in cmake behind compile flag

third-party/targets.bzl
Manually build with oss buck from ET:
```
buck2-bin/buck2-edae27cfca00053d9c5f7c7be81b6b0d7d07573a50be374ce53a9d8692afa5fc build //extension/llm/tokenizers/third-party:pcre2
```
And cquery the Llama runner:
```
buck2-bin/buck2-edae27cfca00053d9c5f7c7be81b6b0d7d07573a50be374ce53a9d8692afa5fc cquery "inputs(deps('//examples/models/llama/runner:runner'))"
```
=> Fix pcre2 target

targets.bzl
Resolve duplicate bpe tokenizer base srcs, causing duplicate symbol linker issues when runner depends on both hf_tokenizer and tiktoken
=> Fix duplicate bpe tokenizer base symbol

targets.bzl
Differential Revision: D73875806
=> Forward fix missing vtable for bpe tokenizer

include/pytorch/tokenizers/bpe_tokenizer_base.h, src/hf_tokenizer.cpp, src/tiktoken.cpp
Handles special tokens before pretokenization and splitting in the c++ huggingface tokenizer.
Llama runner output now with special tokens + json tokenizer:
```
cmake-out/examples/models/llama/llama_main --model_path qwen3-0_6B_long_context.pte --tokenizer_path ./qwen3
_tokenizer/tokenizer.json --prompt="<|im_start|>system                                     
You are a helpful assistant.                                                               
<|im_end|>                                                                                                                                                                            
<|im_start|>user                                                                           
Tell me a story about Julius Caesar<|im_end|> …
```
=> Fix tokenizer special token handling

targets.bzl
Summary:
Use look ahead feature in fbcode.
Add new targets with `-DSUPPORT_REGEX_LOOKAHEAD=ON`
Differential Revision: D74864197
=> Add look ahead tiktoken target

include/pytorch/tokenizers/tokenizer.h
Summary:
Add `is_loaded()` API to `tokenizer.h`
Differential Revision: D73165546
=> Add is_loaded() API

CMakeLists.txt, Utils.cmake, include/pytorch/tokenizers/error.h, include/pytorch/tokenizers/pcre2_regex.h, include/pytorch/tokenizers/regex.h, src/regex.cpp, src/regex_lookahead.cpp, targets.bzl
Declare and define a weak symbol `create_fallback_regex`, the default implementation is returning an error.
We then build a separate target `regex_lookahead` for PCRE2 and std::regex, to support lookahead feature. This library can be optionally linked into the binary.
=> Use weak symbol create_fallback_regex to separate the implementation using PCRE2 and std::regex

include/pytorch/tokenizers/pcre2_regex.h, include/pytorch/tokenizers/re2_regex.h, include/pytorch/tokenizers/regex.h, include/pytorch/tokenizers/std_regex.h, src/pcre2_regex.cpp, src/re2_regex.cpp, src/regex.cpp, src/regex_lookahead.cpp, src/std_regex.cpp, targets.bzl, test/targets.bzl
Summary:
As titled. We can't use weak symbol in fbcode since by default libraries are built in shared libraries and weak symbol doesn't work well with shared libraries.
Basically the dynamic linker will resolve to the first definition it finds, so strong symbol will be ignored.
There's an environment variable `LD_DYNAMIC_WEAK` to let `ld` fallback to the old behavior which respects the strong symbol but that's non-standard and support can be dropped.
See https://man7.org/linux/man-pages/man8/ld.so.8.html
As a result, this PR changes the pattern to be using static initializer to override the `create_fallback_regex()` function. 
```
regex_lookahead.so                                   
┌───────────────────────────────────────────────────┐ 
│ …
```
=> Add regex unit tests and enable shared linkage in fbcode

CMakeLists.txt
Regex lookahead wasn't being linked
=> Fix cmake for regex lookahead

CMakeLists.txt, cmake/tokenizers-config.cmake.in, test/CMakeLists.txt
This pull request introduces several enhancements to the `CMakeLists.txt` file and adds a new configuration file for the `tokenizers` package. The changes focus on improving build system support, adding installation rules, and providing a package configuration file for easier integration with other projects.
* [`CMakeLists.txt`](diffhunk://#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aR24-R27): Included `CMakePackageConfigHelpers` to enable the use of `configure_package_config_file` for generating CMake configuration files.
* [`CMakeLists.txt`](diffhunk://#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aL60-R68): Updated `target_include_directories` to use `$<BUILD_INTERFACE>` for better handling of include directories during the build process. …
=> Enable install find package

include/pytorch/tokenizers/llama2c_tokenizer.h, include/pytorch/tokenizers/sentencepiece.h, include/pytorch/tokenizers/tokenizer.h
Summary: Trying to include sentencpiece tokenizer in llm runner result in duplicated definition
Differential Revision: D76631817
=> Consolidate TokenIndex definition

include/pytorch/tokenizers/pre_tokenizer.h, src/pre_tokenizer.cpp, test/test_hf_tokenizer.cpp, test/test_isolated_behavior.cpp, test/test_pre_tokenizer.cpp
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #93
* #92
Adding support for `Remove` and `Isolated` behavior.
Currently all the behaviors supported:
* `MergedWithPrevious`
* `Remove`
* `Isolated`
According to the Rust implementation:
```
/// Defines the expected behavior for the delimiter of a Split Pattern
/// When splitting on `'-'` for example, with input `the-final--countdown`:
///  - Removed => `[ "the", "final", "countdown" ]`
///  - Isolated => `[ "the", "-", "final", "-", "-", "countdown" ]`
///  - MergedWithPrevious => `[ "the-", "final-", "-", "countdown" ]`
///  - MergedWithNext => `[ "the", "-final", "-", "-countdown" ]`
///  - Contiguous => `[ "the", "-", "final", "--", "countdown" ]`
```
Manually tested qwen3 tokenizer.json. Will add …
=> Add support for more behavior in Split pretokenizer

include/pytorch/tokenizers/normalizer.h, src/normalizer.cpp, test/test_hf_tokenizer.py, third-party/llama.cpp-unicode/include/unicode.h, third-party/llama.cpp-unicode/src/unicode.cpp
A simplified version of NFC. Based on what we have for NFD, this PR implements the composition logic. Also refer back to https://unicode.org/reports/tr15/ on how this works.
=> Support NFC Normalizer

src/hf_tokenizer.cpp
Summary:
`-Wunused-exception-parameter` has identified an unused exception parameter. This diff removes it.
This:
```
try {
...
} catch (exception& e) {
// no use of e
}
```
should instead be written as
```
} catch (exception&) {
```
If the code compiles, this is safe to land.
Reviewed By: dtolnay
Differential Revision: D79968824
=> Remove unused exception parameter from pymk/aggregator/early_stage_ranking/EarlyStageRanker.cpp

CMakeLists.txt, README.md, include/pytorch/tokenizers/tekken.h, src/python_bindings.cpp, src/tekken.cpp, test/test_tekken.cpp, test/test_tekken_python.py
Add Tekken tokenizer implementation with Python bindings
Implements Mistral's Tekken tokenizer (v7) with comprehensive C++ implementation
and Python bindings. Provides significant efficiency gains for AI workloads
while maintaining 100% decode accuracy and compatibility with mistral-common.
- **C++ Tekken tokenizer**: Full BPE implementation with special token recognition
- **Header file**: include/pytorch/tokenizers/tekken.h with complete API
- **Source file**: src/tekken.cpp with JSON parsing, vocabulary loading, encoding/decoding
- **PCRE2 integration**: Regex fallback for complex lookahead patterns not supported by RE2
- **Special token efficiency**: [INST], [/INST], [AVAILABLE_TOOLS], etc. as single tokens (3-7x fewer tokens)
- **Multilingual support**: Complete Unicode handling …
=> Add Tekken tokenizer implementation with Python bindings

examples/tokenize_tool/main.cpp
```
>> cmake -DTOKENIZERS_BUILD_TOOLS=ON -DSUPPORT_REGEX_LOOKAHEAD=ON . -Bbuild && cmake --build build -j9
>> ./build/examples/tokenize_tool/tokenize_tool tekken ~/hf/models--mistralai--Voxtral-Mini-3B-2507/snapshots/3060fe34b35ba5d44202ce9ff3c097642914f8f3/tekken.json "<s>[INST]Let's go swim at the beach!"
I tokenizers:regex.cpp:27] Registering override fallback regex
I tokenizers:tekken.cpp:88] Loading Tekken tokenizer from: /home/jackzhxng/hf/models--mistralai--Voxtral-Mini-3B-2507/snapshots/3060fe34b35ba5d44202ce9ff3c097642914f8f3/tekken.json
I tokenizers:tekken.cpp:112] Tekken version: v7, vocab_size: 131072, special_tokens: 1000
I tokenizers:tekken.cpp:123] Loading special tokens from JSON
I tokenizers:tekken.cpp:282] Initialized 1000 special tokens (1000 defined, 0 placeholders)
I …
```
=> Add tekken to the tokenize tool

.github/workflows/pull.yml, .gitignore, CMakeLists.txt, include/pytorch/tokenizers/compiler.h, include/pytorch/tokenizers/tiktoken.h, setup.py, src/hf_tokenizer.cpp, test/test_tiktoken.cpp
This PR adds support for building with Clang-CL on Windows, as well as CI to cover this.
Changes:
* Update CMake to not pass `-Wno-attributes` on Windows. MSVC and Clang-CL don't accept this option.
* Alias ssize_t to SSIZE_T on Windows.
* Update CMake build in setup.py to use Clang-CL and use namespaced extension name (this makes it work without playing with paths).
* Explicitly call .string() on std::filesystem::paths. The implicit conversion works on Clang/GCC but not with MSVC/Clang-CL.
* Add a Windows job to build and run tests.
Fixes https://github.com/meta-pytorch/tokenizers/issues/111.
Test Plan:
I've add CI to run native and Python unit tests on Windows. I've also verified locally that editable and non-editable installs work on both Linux and Windows.
=> [Windows] Fix build issues using Clang-CL on Windows, add CI

include/pytorch/tokenizers/tekken.h, targets.bzl
Summary:
allow-large-files
bypass-github-export-checks
bypass-github-pytorch-ci-checks
bypass-github-executorch-ci-checks
bypass-github-torchtune-ci-checks
diff-train-skip-merge
Reviewed By: jackzhxng
Differential Revision: D81598484
=> Forward fix tekken tokenizer for internal test

cmake/tokenizers-config.cmake.in
The tokenizers-config CMake file needs to be updated to use the .lib extension on Windows, instead of .a, for the tokenizers library. This allows tokenizers to be referenced via find_package on Windows. This was an oversight in https://github.com/meta-pytorch/tokenizers/pull/121.
=> Update tokenizers-config for Windows

src/hf_tokenizer.cpp, src/pre_tokenizer.cpp, test/test_hf_tokenizer.py, third-party/targets.bzl
Summary:
- Add Phi4 test
- Handle the invert flag properly
- Skip regex lookahead since it's not supported by RE2
- Catch std::exception instead of narrow json parser errors
- Make the special tokens arg optional in ObjC/Swift API
Differential Revision: D83641294
=> Add Phi4 test and fix regex parsing.
